#! /bin/bash

# 以下配置需要手动输入

# 远程系统相关配置
# user=
# host=

# 各个系统下不同的设置

# 用 open 别名打开本地管理器
# Arch Linux
# alias open='xdg-open'
# Windows WSL
# alias open='explorer.exe'

# JAVA_HOME
# Arch Linux
# export JAVA_HOME='/usr/lib/jvm/java-11-openjdk'
# export PATH=$JAVA_HOME/bin:$PATH
# Ubuntu
# export JAVA_HOME='/usr/lib/jvm/java-11-openjdk-amd64'
# export PATH=$JAVA_HOME/bin:$PATH

# Update Arch Linux and yay
# alias P="sudo pacman -Syu"
# alias Y="yay -Syu"
