#! /bin/bash

# 各个系统下不同的设置

# 修复 wsl 下光标消失的问题
# echo -n -e "\033[?25h"

# 用 open 别名打开本地管理器
# Arch Linux
# alias open='xdg-open'
# Windows WSL
# alias open='explorer.exe'

# 重启 clash 服务
# alias clashRestart='sudo systemctl restart clash'

# 登录远程系统
# alias login="ssh user@host"

# JAVA_HOME
# Arch Linux
# export JAVA_HOME='/usr/lib/jvm/java-11-openjdk'
# Ubuntu
# export JAVA_HOME='/usr/lib/jvm/java-11-openjdk-amd64'
# export PATH=$JAVA_HOME/bin:$PATH
