#! /bin/bash

# 以下配置需要手动输入

# 远程系统相关配置
# user=
# host=
# clashUrl=""

# 各个系统下不同的设置

# 修复 wsl 下光标消失的问题
# echo -n -e "\033[?25h"

# 用 open 别名打开本地管理器
# Arch Linux
# alias open='xdg-open'
# Windows WSL
# alias open='explorer.exe'

# 重启 clash 服务
# alias clashRestart="sudo systemctl restart clash"
# 更新 clash
# alias clashUpdate="wget -O ~/.config/clash/config.yaml '$clashUrl'"

# 登录远程系统
# alias login="ssh $user@$host"

# 上传JD_COOKIE到远程系统
# alias pushJ="scp ~/.jdrc $user@$host:.jdrc"

# 开启远程服务器代理
# alias lp="autossh -M 7700 -D 7891 $user@$host -N -f"

# JAVA_HOME
# Arch Linux
# export JAVA_HOME='/usr/lib/jvm/java-11-openjdk'
# export PATH=$JAVA_HOME/bin:$PATH
# Ubuntu
# export JAVA_HOME='/usr/lib/jvm/java-11-openjdk-amd64'
# export PATH=$JAVA_HOME/bin:$PATH

# Update Arch Linux and yay
# alias P="sudo pacman -Syu"
# alias Y="yay -Syu"
#
# export npm_config_platform=win32
